delete test.sh

diff --git a/bin/hcc b/bin/hcc
--- a/bin/hcc
+++ b/bin/hcc
@@ -2,6 +2,39 @@
 
 # set -euo pipefail
 
+testold() {
+    i=$(basename $1)
+    qfile=testold/question/$i
+    afile=testold/answer/$i
+    expected="$(cat $afile)"
+
+    ./bin/exe.out $qfile >tmp.s
+    cc -o tmp tmp.s helper/helper.c # シンプルなテストなのでstaticをつけなくてもよい
+    printf $qfile
+    ./tmp
+    actual="$?"
+    if [ "$actual" = "$expected" ]; then
+        printf "...passed\n"
+    else
+        printf "...failed\n"
+        exit 1
+    fi
+}
+
+test() {
+    filename=$1
+    ./bin/exe.out $filename >tmp.s
+    cc -static -o tmp tmp.s helper/helper.c
+    printf $filename
+    ./tmp
+    if [ $? = 0 ]; then
+        printf "...passed\n"
+    else
+        printf "...failed\n"
+        result=1
+    fi
+}
+
 if [ $# -eq 0 ]; then
     echo "引数なしでは実行できません"
     exit 1
@@ -33,21 +66,18 @@ elif [ $1 = "asmdr" ]; then
     objdump -d -M Intel a.o
     rm a.o tmp.c
 elif [ $1 = "testold" ]; then
-    docker-compose run hooligan make test
+    docker-compose run hooligan ./bin/hcc testolddr
+elif [ $1 = "testolddr" ]; then
+    make
+    for fn in testold/question/*; do
+        testold $fn
+    done
+    rm tmp.s tmp
 elif [ $1 = "testv2dr" ]; then
     make
     result=0
     for fn in test/*; do
-        ./bin/exe.out $fn >tmp.s
-        cc -static -o tmp tmp.s helper/helper.c
-        printf $fn
-        ./tmp
-        if [ $? = 0 ]; then
-            printf "...passed\n"
-        else
-            printf "...failed\n"
-            result=1
-        fi
+        test $fn
     done
     rm tmp.s tmp
     exit $result
